import type { WordPressThemeProfile } from "../../types";

export const WORDPRESS_DEFAULT_NAMING = "{profilo}-{componente}-{slug}-{w}x{h}";

export const WORDPRESS_THEME_PROFILES: WordPressThemeProfile[] = [
  {
    id: "generic-editorial",
    name: "Editoriale Generico",
    description: "Blog, pagine servizi e contenuti hero per temi WordPress classici.",
    note: "Buon punto di partenza per siti editoriali e landing con immagini di copertina.",
    components: [
      {
        id: "hero-banner",
        name: "Hero Banner",
        description: "Hero desktop ampia per pagine marketing o homepage.",
        width: 1920,
        height: 720,
        suffix: "_hero-banner",
        defaultEnabled: true,
      },
      {
        id: "featured-post",
        name: "Featured Post",
        description: "Immagine principale articolo o archivio blog.",
        width: 1200,
        height: 800,
        suffix: "_featured-post",
        defaultEnabled: true,
      },
      {
        id: "card-thumb",
        name: "Card Thumbnail",
        description: "Card lista articoli, blocchi editoriali e loop secondari.",
        width: 640,
        height: 420,
        suffix: "_card-thumb",
        defaultEnabled: true,
      },
      {
        id: "author-avatar",
        name: "Author Avatar",
        description: "Avatar autore o team nelle pagine contenuto.",
        width: 160,
        height: 160,
        suffix: "_author-avatar",
      },
      {
        id: "footer-logo",
        name: "Footer Logo",
        description: "Logo orizzontale per footer o barra partner.",
        width: 240,
        height: 80,
        suffix: "_footer-logo",
      },
    ],
  },
  {
    id: "woocommerce-standard",
    name: "WooCommerce Standard",
    description: "Preset concreti per prodotto, galleria, category e carrello.",
    note: "Pensato per mantenere consistenza tra PDP, listing e miniature di checkout.",
    components: [
      {
        id: "product-main",
        name: "Product Main",
        description: "Immagine principale prodotto ad alta definizione.",
        width: 1400,
        height: 1400,
        suffix: "_product-main",
        defaultEnabled: true,
      },
      {
        id: "product-gallery",
        name: "Product Gallery",
        description: "Varianti gallery zoomabili e slide prodotto.",
        width: 1200,
        height: 1200,
        suffix: "_product-gallery",
        defaultEnabled: true,
      },
      {
        id: "product-thumb",
        name: "Product Thumbnail",
        description: "Miniatura listing, related e suggestioni prodotto.",
        width: 360,
        height: 360,
        suffix: "_product-thumb",
        defaultEnabled: true,
      },
      {
        id: "cart-thumb",
        name: "Cart Thumbnail",
        description: "Miniatura leggera per carrello, mini-cart e checkout.",
        width: 120,
        height: 120,
        suffix: "_cart-thumb",
      },
      {
        id: "category-banner",
        name: "Category Banner",
        description: "Banner largo per categorie e pagine collezione.",
        width: 1600,
        height: 520,
        suffix: "_category-banner",
      },
    ],
  },
  {
    id: "elementor-landing",
    name: "Elementor Landing",
    description: "Blocchi hero, media card e contenuti responsive da landing builder.",
    note: "Profilo adatto a landing con blocchi visuali e componenti duplicati desktop/mobile.",
    components: [
      {
        id: "hero-desktop",
        name: "Hero Desktop",
        description: "Visual principale full-width per sezioni above the fold.",
        width: 1920,
        height: 840,
        suffix: "_hero-desktop",
        defaultEnabled: true,
      },
      {
        id: "hero-mobile",
        name: "Hero Mobile",
        description: "Versione mobile del visual principale.",
        width: 768,
        height: 960,
        suffix: "_hero-mobile",
        defaultEnabled: true,
      },
      {
        id: "content-image",
        name: "Content Image",
        description: "Blocco immagine affiancato a testo o media & text.",
        width: 920,
        height: 640,
        suffix: "_content-image",
        defaultEnabled: true,
      },
      {
        id: "testimonial-avatar",
        name: "Testimonial Avatar",
        description: "Avatar circolare o quadrato per prove sociali.",
        width: 180,
        height: 180,
        suffix: "_testimonial-avatar",
      },
      {
        id: "logo-strip",
        name: "Logo Strip",
        description: "Logo partner e social proof in strisce orizzontali.",
        width: 260,
        height: 90,
        suffix: "_logo-strip",
      },
    ],
  },
];
